[package]
name = "asteroid-tui"
version = "0.1.0"
authors = ["Sirio Negri <ziriuz84@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
config = "0.14.0"
crossterm = "0.27.0"
dirs = "5.0.1"
ratatui = "0.26.1"
reqwest = {version = "0.12.1", features = ["blocking","json"]}
scraper = "0.19.0"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.115"
serde_repr = "0.1.18"
