sonar.projectKey=ziriuz84_asteroid_tui_db179ce9-75c4-4e23-bf90-8f667e10b978
sonar.projectName=asteroid-tui

sonar.host.url=https://sq.casapomininegri.it

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.rust.clippy.enabled=true
sonar.rust.lcov.reportPaths=lcov.info

sonar.exclusions=**/target/**,**/*.bk
